### ISSUE TITLE
Escrever a premissa do jogo

### ISSUE THREAD

**Issue by boidacarapreta** [boidacarapreta/adcipt20231#1]

**Comment by Higorass** [comment]
Don't look será um jogo de terror, onde contara a história de dois gêmeos que vivem em paralelos diferentes, onde a partir de um fenômeno mistico eles descobrem a exitância um do outro, e acabam entrando em uma busca perigosa pra se encontrar .
Os eventos ocorrerão um um orfanato, onde ao primeiro gêmeo (Theo) vivera no ano 2023. Uma velha mansão que aloja algumas crianças que não foram adotadas até seus 8 anos, onde Theo. Já a outra gemea (katie) iniciara sua busca por uma família em uma nova mansão, construída 1h da cidade na época de 1953, ela só não imaginava como sua família estaria tão perto e longe ao mesmo tempo.

**Comment by boidacarapreta** [comment]
> Don't look será um jogo de terror, onde contara a história de dois gêmeos que vivem em paralelos diferentes, onde a partir de um fenômeno mistico eles descobrem a exitância um do outro, e acabam entrando em uma busca perigosa pra se encontrar . Os eventos ocorrerão um um orfanato, onde ao primeiro gêmeo (Theo) vivera no ano 2023. Uma velha mansão que aloja algumas crianças que não foram adotadas até seus 8 anos, onde Theo. Já a outra gemea (katie) iniciara sua busca por uma família em uma nova mansão, construída 1h da cidade na época de 1953, ela só não imaginava como sua família estaria tão perto e longe ao mesmo tempo.

Copiei para a tua tarefa, @Higorass, ok?

**Comment by boidacarapreta** [comment]
Premissa escrita no README do repositório.
