### ISSUE TITLE
Publicar o Canvas

### ISSUE THREAD

**Issue by ghost** [boidacarapreta/adcipt20231#55]
Tornar pública a URL do Canvas do jogo.

**Comment by boidacarapreta** [comment]
Arquivo [canvas-1097133-20230303141403.pdf](https://github.com/boidacarapreta/adcipt20231/files/11092441/canvas-1097133-20230303141403.pdf) ([versão online](https://canvas-apps.pr.sebrae.com.br/canvas-api/shared/ae96fb8d-496d-49f0-bf91-cdd436060436/1097133)).
